# CI/PR Pipeline that deploys an ARM template to create or update the resources needed by the other pipelines.
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - 00_iac/arm-templates/*
pr:
  branches:
    include:
      - master
  paths:
    include:
      - 00_iac/arm-templates/*

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: devops-iac-vg

steps:
  - task: AzureResourceGroupDeployment@2
    inputs:
      azureSubscription: "$(AZURE_RM_SVC_CONNECTION)"
      action: "Create Or Update Resource Group"
      resourceGroupName: "$(RESOURCE_GROUP)"
      location: $(LOCATION)
      templateLocation: "Linked artifact"
      csmFile: "$(Build.SourcesDirectory)/00_iac/arm-templates/cloud-environment.json"
      overrideParameters: "- -baseName $(BASE_NAME) -location $(LOCATION) -sqlAdministratorLogin $(SQL_ADMINISTRATOR_LOGIN) -sqlAdministratorLoginPassword $(SQL_ADMINISTRATOR_LOGIN_PASSWORD)  -grantPublicIp $(GRANT_PUBLIC_IP) -AzureDatabricksId $(AZURE_DATABRICKS_ID) -DevOpsAppId  $(AZURE_RM_SVC_CON_ID) -VMAdministratorLogin $(VM_ADMINISTRATOR_LOGIN) -VMAdministratorLogin $(VM_ADMINISTRATOR_LOGIN)"
      deploymentMode: "Incremental"
    displayName: "Deploy resources to Azure"
